[package]
name = "problem_details"
version = "0.1.0"
edition = "2021"

[dependencies]
http = "0.2"

# Optional Dependencies
serde = { version = "1.0", features = ["serde_derive"], optional = true }
http-serde = { version = "1.1", optional = true }

[dev-dependencies]
serde_json = "1.0"

[features]
default = ["serde"]
serde = ["dep:serde", "dep:http-serde"]